### ISSUE TITLE
Old version of `num` dependencies prevents usage

### ISSUE THREAD

**Issue by Dessix** [d-e-s-o/num-decimal#1]
Hello - [num has moved up to version 4](https://github.com/d-e-s-o/num-decimal/blob/master/Cargo.toml) for most of its crates.

Trying to use a newer version results in `BigInt` mismatches, which prevent dividing `Num` instances by `BigInt` at all.

**Comment by d-e-s-o** [comment]
Good point. I see that I even forgot to push changes bumping those dependencies to `0.3` that I had created back in February.

**Comment by d-e-s-o** [comment]
You can use version `0.2.4` of the crate with `default-features = false, features = ["num-v04"]` to get the `0.4` versions of `num-bigint` and `num-rational` pulled in instead of the `0.2` ones, which are still the default.
